version: "3"
services:
  free-money-web:
    build: ./FreeMoney.Web
    ports:
      - "80:80"
    environment:
      - FREE_MONEY_CONNECTION_STRING=${FREE_MONEY_CONNECTION_STRING}
      - AZURE_FUNCTION_REGISTER_USER_RECORD=${AZURE_FUNCTION_REGISTER_USER_RECORD}
